server:
  port: 8080

endpoints:
  info:
    id: information
    sensitive: false
    enabled: true
information:
  app:
    name: UsersApplication
    description: User Microservice
    version: 1.0.0
managment:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: user-microservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

album-microservice:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081